url = https://www.saucedemo.com/
username = standard_user
password = secret_sauce

apiBaseUrl = https://api.restful-api.dev/objects

#set le -> local execution, he -> headless execution , ce -> containerize execution
testExecutionStrategy = le
#browser = edge #browser is passed via TestNG parameters